name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, reasonable-comp-calculator ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: reasonablecomp/package-lock.json
    
    - name: Install dependencies
      run: |
        cd reasonablecomp
        npm ci
    
    - name: Build Next.js app
      run: |
        cd reasonablecomp
        npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reasonablecomp/out
        destination_dir: reasonablecomp 