name: Deploy to GitHub Pages (Actions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: reasonablecomp/package.json

      # Build Reasonable Comp app
      - name: Install deps (Reasonable Comp)
        working-directory: ./reasonablecomp
        run: npm install
      
      - name: Build Reasonable Comp
        working-directory: ./reasonablecomp
        run: npm run build

      # Assemble single artifact
      - name: Assemble site
        run: |
          rm -rf dist
          mkdir -p dist/statetax dist/reasonablecomp
          echo "tools.cardifftax.com" > dist/CNAME
          
          # Copy existing statetax files (already working)
          cp -a statetax/* dist/statetax/
          
          # Copy reasonablecomp build output
          cp -a reasonablecomp/out/* dist/reasonablecomp/
          
          # Create SPA fallbacks for client-side routing
          cp dist/statetax/index.html dist/statetax/404.html || true
          cp dist/reasonablecomp/index.html dist/reasonablecomp/404.html || true
          
          # Copy root files
          cp index.html dist/ || true
          
          # Show what we're deploying
          echo "Deploying structure:"
          find dist -type f | head -20

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
